export const copy = {
  es: {
    home: 'Inicio', calculator: 'Calculadora', methodology: 'Metodología', language: 'Idioma', skip: 'Saltar al contenido',
    eyebrow: 'TU SALARIO, MÁS CLARO', title: 'Del bruto al neto, sin complicaciones.', intro: 'Entiende cuánto recibirías y compara tu salario con una estimación clara para España y Francia.', cta: 'Calcular mi salario neto', countries: 'Países admitidos', spain: 'España', france: 'Francia', stepsTitle: 'Tres pasos para entender tu salario', steps: ['Elige el país donde trabajas.', 'Introduce tu salario bruto y los datos necesarios.', 'Consulta tu estimación de salario neto y su desglose.'], privacyTitle: 'Tus datos se quedan contigo', privacy: 'Sin registro. Los cálculos se realizan en tu dispositivo: tus datos salariales no se envían a un servidor.', independent: 'Puedes elegir el idioma independientemente del país.', calcIntro: 'Este es el punto de entrada de la calculadora para España y Francia.', pending: 'La introducción de salario y el motor de cálculo se incorporarán en las próximas historias. Todavía no se generan estimaciones.', methodIntro: 'La estimación se realizará localmente con reglas versionadas para cada país, sin llamadas a servicios fiscales durante el cálculo.', limits: 'Los resultados serán orientativos. Las reglas fiscales, sus fuentes y supuestos se documentarán junto con el motor de cálculo.', back: 'Volver al inicio', missing: 'Página no encontrada', missingText: 'Esta dirección no existe. Puedes volver al inicio o acceder a la calculadora.', footer: 'España y Francia · Sin registro · Datos locales',
  },
  fr: {
    home: 'Accueil', calculator: 'Calculateur', methodology: 'Méthodologie', language: 'Langue', skip: 'Aller au contenu',
    eyebrow: 'VOTRE SALAIRE, PLUS CLAIR', title: 'Du brut au net, simplement.', intro: 'Comprenez ce que vous percevriez et comparez votre salaire grâce à une estimation claire pour l’Espagne et la France.', cta: 'Calculer mon salaire net', countries: 'Pays disponibles', spain: 'Espagne', france: 'France', stepsTitle: 'Trois étapes pour comprendre votre salaire', steps: ['Choisissez votre pays de travail.', 'Saisissez votre salaire brut et les informations nécessaires.', 'Consultez votre estimation de salaire net et son détail.'], privacyTitle: 'Vos données restent avec vous', privacy: 'Sans inscription. Les calculs sont effectués sur votre appareil : vos données salariales ne sont pas envoyées à un serveur.', independent: 'La langue peut être choisie indépendamment du pays.', calcIntro: 'Voici le point d’entrée du calculateur pour l’Espagne et la France.', pending: 'La saisie du salaire et le moteur de calcul seront ajoutés dans les prochaines fonctionnalités. Aucune estimation n’est encore produite.', methodIntro: 'L’estimation sera effectuée localement avec des règles versionnées par pays, sans appel aux services fiscaux pendant le calcul.', limits: 'Les résultats seront indicatifs. Les règles fiscales, leurs sources et hypothèses seront documentées avec le moteur de calcul.', back: 'Retour à l’accueil', missing: 'Page introuvable', missingText: 'Cette adresse n’existe pas. Vous pouvez revenir à l’accueil ou ouvrir le calculateur.', footer: 'Espagne et France · Sans inscription · Données locales',
  },
  en: {
    home: 'Home', calculator: 'Calculator', methodology: 'Methodology', language: 'Language', skip: 'Skip to content',
    eyebrow: 'YOUR SALARY, MADE CLEAR', title: 'From gross to net, without the guesswork.', intro: 'Understand what you would take home and compare your salary with a clear estimate for Spain and France.', cta: 'Calculate my net salary', countries: 'Supported countries', spain: 'Spain', france: 'France', stepsTitle: 'Three steps to understand your salary', steps: ['Choose the country where you work.', 'Enter your gross salary and the required details.', 'View your estimated net salary and its breakdown.'], privacyTitle: 'Your data stays with you', privacy: 'No registration required. Calculations run on your device: your salary data is not sent to a server.', independent: 'You can choose your language independently of the country.', calcIntro: 'This is the entry point for the calculator for Spain and France.', pending: 'Salary entry and the calculation engine will be added in upcoming stories. Estimates are not generated yet.', methodIntro: 'Estimates will run locally using versioned rules for each country, without calls to tax services during calculation.', limits: 'Results will be indicative. Tax rules, sources and assumptions will be documented alongside the calculation engine.', back: 'Back to home', missing: 'Page not found', missingText: 'This address does not exist. You can return home or open the calculator.', footer: 'Spain and France · No registration · Local data',
  },
};
export type Language = keyof typeof copy;
